### ISSUE TITLE
Update eos-rs for pmdsky-debug "Include secondary genders in enum monster_id"

### ISSUE THREAD

**Issue by theCapypara** [SkyTemple/c-of-time#155]
Update eos-rs for https://github.com/UsernameFodder/pmdsky-debug/pull/94

**Comment by UsernameFodder** [comment]
This was just adding variants to `enum monster_id`. I imagine bindgen should handle this automatically, but not 100% sure.

**Comment by theCapypara** [comment]
Probably best to check, also for some enums I added easier-to-use abstractions, need to check again.
