### ISSUE TITLE
Update eos-rs for pmdsky-debug "Post-spreadsheet-migration: run symbols_vfill.py"

### ISSUE THREAD

**Issue by theCapypara** [SkyTemple/c-of-time#159]
Update eos-rs for https://github.com/UsernameFodder/pmdsky-debug/pull/100

**Comment by UsernameFodder** [comment]
I think there's nothing to do here, it was just adding JP offsets and reordering symbols.

**Comment by theCapypara** [comment]
:+1: I just did a glance if symbol files were changed and didn't review the contents yet, so thanks for letting me know.
