### ISSUE TITLE
Update eos-rs for Metalcape's status and enemy spawn updates

### ISSUE THREAD

**Issue by theCapypara** [SkyTemple/c-of-time#24]
See
https://github.com/UsernameFodder/pmdsky-debug/pull/50

**Comment by tech-ticks** [comment]
Dependabot handled this one: https://github.com/tech-ticks/c-of-time/pull/25

**Comment by theCapypara** [comment]
oh actually, I was thinking of the update of the high level bindings, not just the ffi. Plus without changing the high level bindings it probably won't compile now. 


Also applies to the other PR.
