### ISSUE TITLE
CI doesn't execute on pmdsky-debug submodule update

### ISSUE THREAD

**Issue by tech-ticks** [SkyTemple/c-of-time#26]
Caused by the `paths` filter here: https://github.com/tech-ticks/c-of-time/blob/main/.github/workflows/rust-check-ffi.yml#L3

This filter should be changed or removed to ensure that the Rust bindings are validated before updating `pmdsky-debug`

**Comment by theCapypara** [comment]
ah right, probably just need to add /pmdsky-debug as well.

**Comment by tech-ticks** [comment]
I've removed the filter for now to unblock the CI, we can follow up with a proper filter later. It should also include `.github/` so that we can test it properly

**Comment by tech-ticks** [comment]
I guess the CI setup is fine as-is right now, feel free to comment or reopen if you disagree.
