### ISSUE TITLE
Update eos-rs for pmdsky-debug "Add/support global variable declarations for data symbols in C headers"

### ISSUE THREAD

**Issue by theCapypara** [SkyTemple/c-of-time#98]
Update eos-rs for https://github.com/UsernameFodder/pmdsky-debug/pull/73

There's probably not much (if anything) that needs to be done, but maybe some global variables could get safe wrappers?

**Comment by UsernameFodder** [comment]
At the very least, there were a couple function parameter type tweaks, and also one new function called `GetRankUpEntry`
